version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - flask_db
    networks:
      - app_network
  flask_db:
    container_name: flask_db
    image: 'postgres:12'
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgdata: {}

networks:
  app_network:
    driver: bridge
    name: app_network
